name: ci
on:
  push:
    branches:
      - main
jobs:
  tasks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo service mysql stop
          sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
          sudo apt-get autoremove -y
          sudo apt-get autoclean
          sudo rm -rf /etc/mysql
          sudo rm -rf /var/lib/mysql
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: mariadb
          args: start
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: laravel
      - name: test
        run: fluentci run --wasm laravel test
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARIADB_DATABASE: laravel
          MARIADB_USER: user
          MARIADB_PASSWORD: password
